# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zynq_pin.xdc

# IP: E:/FPGA/vivado/HDMI_DEMO_2017_03_28_01/Miz702_VGA/vivado_prj/miz702_vga/miz702_vga.srcs/sources_1/ip/rom_pic/rom_pic.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_pic || ORIG_REF_NAME==rom_pic}]
