# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/FPGA/vivado/HDMI_DEMO_2017_03_28_01/hdmi_display_demon/hdmi_display_demon.srcs/sources_1/ip/image_rom/image_rom.xci
# IP: The module: 'image_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/vivado/HDMI_DEMO_2017_03_28_01/hdmi_display_demon/hdmi_display_demon.srcs/sources_1/ip/image_rom/image_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/FPGA/vivado/HDMI_DEMO_2017_03_28_01/hdmi_display_demon/hdmi_display_demon.srcs/sources_1/ip/image_rom/image_rom.xci
# IP: The module: 'image_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/vivado/HDMI_DEMO_2017_03_28_01/hdmi_display_demon/hdmi_display_demon.srcs/sources_1/ip/image_rom/image_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
